### ISSUE TITLE
failed to generate diff

### ISSUE THREAD

**Issue by maltfield** [khimaros/freecad-build#1]
I'm getting the following error when I attempt to use this tool to diff two FreeCAD files

```
!!! failed to generate diff for /tmp/meshdiff.GzagNrvO/modified/intake.step in /tmp/meshdiff.GzagNrvO
```
# Steps to Reproduce

Here's the commands I ran:

```
git clone https://github.com/khimaros/freecad-build.git

# main repo with old file to diff
git clone https://github.com/Eco-Libre/life-line.git
mv life-line/ eco-libre-life-line
cd eco-libre-life-line
git reset --hard e253913e2b06574ef150e16a960c00321d0d160f
cd ..

# forked repo with new file to diff
git clone https://github.com/Matterhorn777/life-line.git
mv life-line matterhorn777-life-line
cd matterhorn777-life-line
git reset --hard 362ec16ce9a9391e0a2766ea2841d9d87ef574eb
cd ..

# make step files
cd freecad-build/
./freecad-export ../eco-libre-life-line/intake.FCStd ../eco-libre-life-line/intake.step
./freecad-export ../matterhorn777-life-line/intake.FCStd ../matterhorn777-life-line/intake.step

# do diff
./freecad-diff ../eco-libre-life-line/intake.step ../matterhorn777-life-line/intake.step 
```

# Full Output

Here is the complete output of the last command (with error and traceback)

```
user@eco-libre:~/sandbox/freecad-build$ ./freecad-diff ../eco-libre-life-line/intake.step ../matterhorn777-life-line/intake.step 
>>> starting freecad-diff ../eco-libre-life-line/intake.step ../matterhorn777-life-line/intake.step
FreeCAD 0.20.2, Libs: 0.20.2R
(c) Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2022
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

### loading document /tmp/meshdiff.nUaFqGNL/previous/intake.step step
### active document 
Recompute......
### finding part with label intake
### found labeled part
### found usable part Unnamed#Part__Feature Part::Feature
Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: cannot read STEP file
Exception while processing file: /tmp/meshdiff.nUaFqGNL/previous.step [cannot read STEP file]
FreeCAD 0.20.2, Libs: 0.20.2R			(100 %)		
(c) Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2022
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

### loading document /tmp/meshdiff.nUaFqGNL/modified/intake.step step
### active document 
Recompute......
### finding part with label intake
### found labeled part
### found usable part Unnamed#Part__Feature Part::Feature
Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: cannot read STEP file
Exception while processing file: /tmp/meshdiff.nUaFqGNL/modified.step [cannot read STEP file]
FreeCAD 0.20.2, Libs: 0.20.2R			(100 %)		
(c) Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2022
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

### loading document /tmp/meshdiff.nUaFqGNL/modified.step step
Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: cannot read STEP file
Exception while processing file: /tmp/meshdiff.nUaFqGNL/modified.step [cannot read STEP file]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: cannot read STEP file
Exception while processing file: /tmp/meshdiff.nUaFqGNL/previous.step [cannot read STEP file]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: cannot read STEP file
Exception while processing file: /tmp/meshdiff.nUaFqGNL/diff-output.step [cannot read STEP file]
!!! failed to generate diff for /tmp/meshdiff.nUaFqGNL/modified/intake.step in /tmp/meshdiff.nUaFqGNL
user@eco-libre:~/sandbox/freecad-build$
```

# Additional Context

I received this error on Debian 12 using the latest version of FreeCAD available in the apt repos as of 2023-12-09

```
user@eco-libre:~$ cat /etc/issue
Debian GNU/Linux 12 \n \l

user@eco-libre:~$ uname -a
Linux eco-libre 6.1.62-1.qubes.fc32.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov 14 07:11:33 CET 2023 x86_64 GNU/Linux
user@eco-libre:~$ sudo dpkg -l | grep -i freecad
ii  freecad                                       0.20.2+dfsg1-4                          all          Extensible Open Source CAx program
ii  freecad-common                                0.20.2+dfsg1-4                          all          Extensible Open Source CAx program - common files
ii  freecad-python3                               0.20.2+dfsg1-4                          amd64        Extensible Open Source CAx program - Python 3 binaries
ii  libfreecad-python3-0.20                       0.20.2+dfsg1-4                          amd64        Extensible Open Source CAx program - Python 3 library files
user@eco-libre:~$ 
```

**Comment by khimaros** [comment]
sorry for the delay, didn't see the notification. 

have you tried inspecting the STEP files generated by the export? just open them with FreeCAD GUI.

**Comment by khimaros** [comment]
@maltfield following up in case you still need assistance.

**Comment by maltfield** [comment]
@khimaros thanks for following-up. I tried to follow my "Steps to Reproduce" above, but now I get an error just trying to `freecad-export` the `.step` files

```
user@disp2745:~/freecad-build$ git remote show origin
* remote origin
  Fetch URL: https://github.com/khimaros/freecad-build.git
  Push  URL: https://github.com/khimaros/freecad-build.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
user@disp2745:~/freecad-build$ 

user@disp2745:~/freecad-build$ git rev-parse HEAD
5d96f0225c711faf0634c254d2217cb281b463ab
user@disp2745:~/freecad-build$ 

user@disp2745:~/freecad-build$ ./freecad-export ../eco-libre-life-line/intake.FCStd ../eco-libre-life-line/intake.step
>>> starting freecad-export ../eco-libre-life-line/intake.FCStd ../eco-libre-life-line/intake.step
FreeCAD 0.20.2, Libs: 0.20.2R
(c) Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2022
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

error: expected 4 arguments, received 3
usage: freecad-export <source> <target>
user@disp2745:~/freecad-build$ 

user@disp2745:~/freecad-build$ ./freecad-export ../matterhorn777-life-line/intake.FCStd ../matterhorn777-life-line/intake.step
>>> starting freecad-export ../matterhorn777-life-line/intake.FCStd ../matterhorn777-life-line/intake.step
FreeCAD 0.20.2, Libs: 0.20.2R
(c) Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2022
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

error: expected 4 arguments, received 3
usage: freecad-export <source> <target>
user@disp2745:~/freecad-build$ 
```

**Comment by maltfield** [comment]
ok ^ that appears to be an unrelated bug introduced in your latest version
 * https://github.com/khimaros/freecad-build/commit/5d96f0225c711faf0634c254d2217cb281b463ab

Probably your scripts should check the version of freecad to determine the arguments so that it continues to work with both old & new versions of FreeCAD. But that's outside the scope of this ticket. For now I'll just manually edit `freecad-export.py` and change the expected args from `4` to `3`

```
user@disp2745:~/freecad-build$ diff freecad-export.py.orig freecad-export.py
11c11
<     if len(sys.argv) != 4:
---
>     if len(sys.argv) != 3:
user@disp2745:~/freecad-build$ 
```

**Comment by maltfield** [comment]
I followed the "Steps to Reproduce" (in OP above) and used `freecad-export` to attempt to build the step files (with the purpose of then doing a diff), but I got the same issue as above

```
user@disp2745:~/freecad-build$ ./freecad-export ../matterhorn777-life-line/intake.FCStd ../matterhorn777-life-line/intake.step
>>> starting freecad-export ../matterhorn777-life-line/intake.FCStd ../matterhorn777-life-line/intake.step
FreeCAD 0.20.2, Libs: 0.20.2R
(c) Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2022
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Importing project files......
Postprocessing......				(100 %)		
Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: cannot read STEP file
Exception while processing file: ../matterhorn777-life-line/intake.step [cannot read STEP file]
user@disp2745:~/freecad-build$
```

> have you tried inspecting the STEP files generated by the export? just open them with FreeCAD GUI.

I tried to open the STEP file in FreeCAD, but FreeCAD gave me the same error

```
user@disp2745:~/freecad-build$ freecad ../matterhorn777-life-line/intake.step
FreeCAD 0.20.2, Libs: 0.20.2R
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2022
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##


(freecad:2138): Gdk-CRITICAL **: 11:16:33.407: gdk_atom_intern: assertion 'atom_name != NULL' failed

(freecad:2138): Gdk-CRITICAL **: 11:16:33.407: gdk_atom_intern: assertion 'atom_name != NULL' failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: cannot read STEP file
Exception while processing file: ../matterhorn777-life-line/intake.step [cannot read STEP file]
[2173:7:0713/111645.721684:ERROR:command_buffer_proxy_impl.cc(141)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
```

The GUI does open (with nothing visible in the CAD panel), and the `Report view` window has the following contents

```
11:16:45  Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: cannot read STEP file
11:16:45  Exception while processing file: ../matterhorn777-life-line/intake.step [cannot read STEP file]
```

**Comment by maltfield** [comment]
It appears that the reason FreeCAD can't read the file is *drum roll* because it doesn't exist!

```
user@disp2745:~/freecad-build$ ls ../matterhorn777-life-line/intake.step
ls: cannot access '../matterhorn777-life-line/intake.step': No such file or directory
user@disp2745:~/freecad-build$ 
```

So, yeah, `freecad-export` just isn't exporting any `.step` file at all.

```
user@disp2745:~/freecad-build$ ./freecad-export ../matterhorn777-life-line/intake.FCStd ../matterhorn777-life-line/intake.step
>>> starting freecad-export ../matterhorn777-life-line/intake.FCStd ../matterhorn777-life-line/intake.step
FreeCAD 0.20.2, Libs: 0.20.2R
(c) Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2022
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Importing project files......
Postprocessing......				(100 %)		
Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: cannot read STEP file
Exception while processing file: ../matterhorn777-life-line/intake.step [cannot read STEP file]
user@disp2745:~/freecad-build$

user@disp2745:~/freecad-build$ ls ../matterhorn777-life-line/intake.FCStd
../matterhorn777-life-line/intake.FCStd
user@disp2745:~/freecad-build$ 

user@disp2745:~/freecad-build$ ls ../matterhorn777-life-line/intake.step
ls: cannot access '../matterhorn777-life-line/intake.step': No such file or directory
user@disp2745:~/freecad-build$ 
```

Any idea how I can debug this further?
